# Generated by Django 3.2.16 on 2022-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocjk', '0016_auto_20221122_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicelement',
            name='lock_key',
            field=models.TextField(blank=True, verbose_name='Lock key'),
        ),
        migrations.AddField(
            model_name='characterglyph',
            name='lock_key',
            field=models.TextField(blank=True, verbose_name='Lock key'),
        ),
        migrations.AddField(
            model_name='deepcomponent',
            name='lock_key',
            field=models.TextField(blank=True, verbose_name='Lock key'),
        ),
    ]
