# Generated by Django 4.1.7 on 2023-02-16 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("robocjk", "0017_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atomicelement",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="atomicelementlayer",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="characterglyph",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="characterglyphlayer",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="deepcomponent",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="font",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="fontimport",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="glyphscomposition",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="editors",
            field=models.ManyToManyField(
                related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
    ]
