# Generated by Django 4.1.7 on 2023-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robocjk", "0018_alter_atomicelement_editors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="font",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, null=True, verbose_name="Slug"
            ),
        ),
    ]
