# Generated by Django 4.1.7 on 2023-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robocjk", "0019_alter_font_slug_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atomicelement",
            name="unicode_hex",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="(unicode hex value, autodetected from xml data)",
                max_length=50,
                verbose_name="Unicode hex",
            ),
        ),
        migrations.AlterField(
            model_name="atomicelementlayer",
            name="unicode_hex",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="(unicode hex value, autodetected from xml data)",
                max_length=50,
                verbose_name="Unicode hex",
            ),
        ),
        migrations.AlterField(
            model_name="characterglyph",
            name="unicode_hex",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="(unicode hex value, autodetected from xml data)",
                max_length=50,
                verbose_name="Unicode hex",
            ),
        ),
        migrations.AlterField(
            model_name="characterglyphlayer",
            name="unicode_hex",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="(unicode hex value, autodetected from xml data)",
                max_length=50,
                verbose_name="Unicode hex",
            ),
        ),
        migrations.AlterField(
            model_name="deepcomponent",
            name="unicode_hex",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="(unicode hex value, autodetected from xml data)",
                max_length=50,
                verbose_name="Unicode hex",
            ),
        ),
    ]
