# Generated by Django 5.0.1 on 2024-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robocjk", "0022_deletedglif_filename_deletedglif_filepath_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atomicelement",
            name="status",
            field=models.CharField(
                db_index=True, default="wip", max_length=20, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="characterglyph",
            name="status",
            field=models.CharField(
                db_index=True, default="wip", max_length=20, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="deepcomponent",
            name="status",
            field=models.CharField(
                db_index=True, default="wip", max_length=20, verbose_name="Status"
            ),
        ),
    ]
